### PR TITLE
CASSANDRASC-54 Add NOTICE.txt file

### PR DESCRIPTION
**Pull request by frankgh**
The NOTICE.txt file is currently missing in the repository. This commit adds the file to comply with ASF's guidance.

### CODE REVIEW

**Comment by michaelsembwever** [comment]
looks good,  but while you're at it i think you should fix (remove) this: https://github.com/apache/cassandra-sidecar/blob/trunk/LICENSE.txt#L205C1-L209 (as there is no lib/ folder)

are you using the rat plugin to check all files have license headers ? 
and checked that all dependencies are apache license compatible?

**Comment by frankgh** [comment]
> looks good, but while you're at it i think you should fix (remove) this: https://github.com/apache/cassandra-sidecar/blob/trunk/LICENSE.txt#L205C1-L209 (as there is no lib/ folder)
> 
> are you using the rat plugin to check all files have license headers ? and checked that all dependencies are apache license compatible?

We are not using the rat plugin, I will take a look at that. Should we do that as a follow up?

**Comment by frankgh** [comment]
> are you using the rat plugin to check all files have license headers ? and checked that all dependencies are apache license compatible?

I ran the rat tool manually. All the source files have license headers. I also checked that all dependencies are ASL compatible. This was a manual process.

**Review by michaelsembwever — APPROVED** [review]

**Comment by michaelsembwever** [comment]
out-of-scope, would it be smart to add the rat plugin as part of the build (in a separate ticket/pr) ?

**Comment by frankgh** [comment]
> out-of-scope, would it be smart to add the rat plugin as part of the build (in a separate ticket/pr) ?

Yes, I will go ahead and create a new ticket for that effort.

**Comment by frankgh** [comment]
Closed via https://github.com/apache/cassandra-sidecar/commit/2cc2eb5844e1f7ec54b2934589c2f4a6a3d226bc

**Pull request closed without merging**
